import type { Metadata } from 'next'
import { requireSession } from '@/lib/auth/session'
import { can } from '@/lib/auth/rbac'
import { getTenant, listGoodsReceipts, listPurchaseOrders, listVendors } from '@/lib/db/repo'
import { Badge, Card, CardBody, CardHeader, EmptyState, PageHeader, Progress, StatTile, StatusBadge, Table } from '@/components/ui/primitives'
import { RankedBars } from '@/components/charts/bar'
import { ActionButton } from '@/components/ui/action'
import { purchaseOrderAction } from '@/app/(app)/actions'
import { formatDate, formatMoney, formatNumber } from '@/lib/utils'

export const metadata: Metadata = { title: 'Purchase orders' }
export const dynamic = 'force-dynamic'

export default async function PurchaseOrdersPage() {
  const session = await requireSession()
  const tenant = getTenant(session.tenantId)
  const currency = tenant.baseCurrency

  const orders = listPurchaseOrders(session.tenantId)
  const receipts = listGoodsReceipts(session.tenantId)
  const vendors = listVendors(session.tenantId)
  const vendorRatings = new Map(vendors.map((v) => [v.id, v.onTimeDeliveryPct]))

  const pendingApproval = orders.filter((po) => po.status === 'Pending Approval' || po.status === 'Draft')
  const inFlight = orders.filter((po) => po.status === 'Approved' || po.status === 'Partially Received')
  const autoGenerated = orders.filter((po) => po.autoGenerated)
  const committed = inFlight.reduce((s, po) => s + po.total, 0)

  const spendByVendor = vendors
    .map((vendor) => ({
      label: vendor.name,
      value: orders.filter((po) => po.vendorId === vendor.id).reduce((s, po) => s + po.total, 0),
    }))
    .filter((row) => row.value > 0)
    .sort((a, b) => b.value - a.value)
    .slice(0, 7)

  const canApprove = can(session, 'po.approve')

  return (
    <>
      <PageHeader
        title="Purchase orders"
        description="Requisition → approval → goods receipt. Receiving a PO moves stock and writes the movement ledger in one transaction."
        meta={
          <>
            <Badge tone="muted">{formatNumber(orders.length)} orders</Badge>
            <Badge tone={pendingApproval.length > 0 ? 'warn' : 'ok'}>{formatNumber(pendingApproval.length)} awaiting approval</Badge>
            <Badge tone="brand">{formatNumber(autoGenerated.length)} auto-generated</Badge>
          </>
        }
      />

      <div className="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-4">
        <StatTile label="Awaiting approval" value={formatNumber(pendingApproval.length)} tone={pendingApproval.length > 0 ? 'warn' : 'ok'} icon="◷" />
        <StatTile label="In flight" value={formatNumber(inFlight.length)} hint={formatMoney(committed, currency, true) + ' committed'} icon="⇄" />
        <StatTile label="Goods receipts" value={formatNumber(receipts.length)} tone="ok" icon="▣" />
        <StatTile label="Raised by the engine" value={formatNumber(autoGenerated.length)} hint="Reorder-point automation" icon="◠" />
      </div>

      <div className="mb-5 grid grid-cols-1 gap-4 xl:grid-cols-3">
        <Card className="xl:col-span-2">
          <CardHeader title="Spend by vendor" subtitle="Total ordered value across all purchase orders" />
          <CardBody>
            <RankedBars data={spendByVendor} format={{ kind: 'money', currency, compact: true }} emptyLabel="No purchase orders yet" />
          </CardBody>
        </Card>

        <Card>
          <CardHeader title="Approval workflow" />
          <CardBody className="space-y-2.5 text-xs leading-relaxed text-ink-muted">
            <p>
              <strong className="text-ink">Draft / Pending Approval</strong> — raised manually or by the reorder engine. Only a Manager or above
              can approve.
            </p>
            <p>
              <strong className="text-ink">Approved</strong> — the vendor is notified through the in-app, email and webhook channels.
            </p>
            <p>
              <strong className="text-ink">Received</strong> — every outstanding line is booked in, stock increases and a goods-receipt note is
              created. Receiving an unapproved PO is rejected.
            </p>
          </CardBody>
        </Card>
      </div>

      <Card>
        <CardHeader title="All purchase orders" subtitle={`${formatNumber(orders.length)} records, newest first`} />
        {orders.length === 0 ? (
          <EmptyState title="No purchase orders" description="Run the reorder engine from the inventory screen to raise the first one." icon="⇄" />
        ) : (
          <Table>
            <thead>
              <tr>
                <th>Order</th>
                <th>Vendor</th>
                <th>Ordered</th>
                <th>Expected</th>
                <th className="text-right">Lines</th>
                <th className="text-right">Value</th>
                <th className="min-w-[110px]">Received</th>
                <th>Status</th>
                <th aria-label="Actions" />
              </tr>
            </thead>
            <tbody>
              {orders.slice(0, 60).map((po) => {
                const ordered = po.lines.reduce((s, l) => s + l.qty, 0)
                const received = po.lines.reduce((s, l) => s + l.qtyReceived, 0)
                const pct = ordered === 0 ? 0 : Math.round((received / ordered) * 100)
                return (
                  <tr key={po.id}>
                    <td>
                      <p className="tnum text-[11px] font-semibold text-ink">{po.number}</p>
                      {po.autoGenerated ? <Badge tone="brand">auto</Badge> : null}
                    </td>
                    <td>
                      <p className="max-w-[170px] truncate text-xs">{po.vendorName}</p>
                      <p className="tnum text-[11px] text-ink-muted">
                        {(vendorRatings.get(po.vendorId) ?? 0).toFixed(0)}% on time
                      </p>
                    </td>
                    <td className="text-xs text-ink-muted">{formatDate(po.orderDate)}</td>
                    <td className="text-xs text-ink-muted">{formatDate(po.expectedDate)}</td>
                    <td className="tnum text-right text-xs">{po.lines.length}</td>
                    <td className="tnum text-right text-xs font-semibold">{formatMoney(po.total, po.currency, true)}</td>
                    <td>
                      <Progress value={pct} tone={pct === 100 ? 'ok' : pct > 0 ? 'warn' : 'muted'} />
                      <span className="tnum mt-1 block text-[10px] text-ink-muted">{pct}%</span>
                    </td>
                    <td>
                      <StatusBadge status={po.status} />
                    </td>
                    <td>
                      <div className="flex justify-end gap-1.5">
                        {canApprove && (po.status === 'Draft' || po.status === 'Pending Approval') ? (
                          <ActionButton action={purchaseOrderAction} fields={{ id: po.id, action: 'approve' }} variant="primary">
                            Approve
                          </ActionButton>
                        ) : null}
                        {canApprove && (po.status === 'Approved' || po.status === 'Partially Received') ? (
                          <ActionButton action={purchaseOrderAction} fields={{ id: po.id, action: 'receive' }} variant="ok">
                            Receive
                          </ActionButton>
                        ) : null}
                      </div>
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </Table>
        )}
      </Card>
    </>
  )
}
